In [80]:
import pandas as pd

df = pd.read_csv("data.csv")

In [81]:
data = pd.read_csv("data.csv")

In [97]:
# Data Preprocessing - Data cleaning

# Drop Id as it doesn't contribute in price
# data.drop(['Id'],
#              axis=1,
#              inplace=True)

# Replacing SalePrice empty values with their mean values
data['SalePrice'] = data['SalePrice'].fillna(
  data['SalePrice'].mean()) 

# Drop records with null values
df = data.dropna()

data.isnull().sum()
data.head()
data.fillna(0, inplace=True)

In [98]:
# Data Preprocessing - Encoding (Covered in Supervised ML Part2)
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
df = pd.get_dummies(data, columns=cols, drop_first=True)

data.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [99]:
# Train-Test Split
from sklearn.model_selection import train_test_split

X = df.drop(['SalePrice'], axis=1)
Y = df['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0)

In [100]:
X_test.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_C (all),MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
1815,30,8520,8,1923,1950,0.0,624.0,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2871,30,8088,3,1922,1955,0.0,498.0,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1232,90,9842,5,1962,1962,0.0,0.0,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1977,60,16451,5,2003,2003,0.0,1765.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
22,20,9742,5,2002,2002,0.0,1777.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [101]:
# Train Linear Regression Model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [96]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print("R2 Score : ",r2_score(y_test,y_pred))

R2 Score :  0.3539449937289141